### ISSUE TITLE
Unable to test Task Completion 

### ISSUE THREAD

**Issue by yifeifeng** [timdohm/de-crast#10]
Summary: Because the apk for Android can not function correctly. We are unable to test the functionality of task completion  when using web browser.

Description:  Because we can not login in with Android device, we are not able to finish a task since it require us to take a photo or provide current location as an evidence. 

Severity: trivial 

Operating System: Firefox web browser

**Comment by jerryand100** [comment]
I re-built the .apk file and verified that it ran on my physical Android device.

I sent liuzhigong666@gmail.com an email containing the .apk file, as you cannot attach a file of that type to a GitHub issue comment.

Please try running the new .apk and let us know if that works, as our application is not designed to be fully functional in a web browser.

**Comment by yifeifeng** [comment]
We just successfully build the app on both Android devices. However we still can not submit the photo evidence for it. The "Submit Photo Evidence" button is not responding.

**Comment by tsealex** [comment]
This has been fixed.
