### ISSUE TITLE
No Viewer displayed despite task being accepted

### ISSUE THREAD

**Issue by AaronHProgramming** [timdohm/de-crast#12]
Expected Behavior: Message in task information should change immediately from No Viewer to Viewer Username when task is accepted.

Actual behavior:
![image](https://cloud.githubusercontent.com/assets/12736560/25552519/6b3ae544-2c61-11e7-86bd-69578c050d98.png) After a long period of time, most of the tasks I have created have changed from No Viewer to Viewer_Username

How can the problem be reproduced: Create a task with a viewer, have viewer accept the task, look at task information

Operating System: Windows 8, Chrome

Severity: Mild

**Comment by jerryand100** [comment]
This has been addressed and taken care of.
