### ISSUE TITLE
Task not removed when completed

### ISSUE THREAD

**Issue by AaronHProgramming** [timdohm/de-crast#13]
Expected Behavior: When completed, task should be removed from both the user and the viewer's displays

Actual behavior: The user who created the task still sees the task
![image](https://cloud.githubusercontent.com/assets/12736560/25552553/62d533cc-2c62-11e7-885d-eaf65ae03b35.png)

How can the problem be reproduced: Create a GPS task. Get Viewer to accept task. Complete task.
No acknowledgement will be shown to the user but it will be removed from the viewers tab without notice.

Operating System: Windows 8, Chrome

Severity: Significant

**Comment by jerryand100** [comment]
This turned out to be a local caching issue. The task was deleted on the server, but the local list used to populate views still had a copy of the task, thus it still showed up.
We refactored our local cache code, and in the process of refactoring, this issue was addressed and taken care of.
