### ISSUE TITLE
Creating a new task is easy to unintentionally duplicate

### ISSUE THREAD

**Issue by AaronHProgramming** [timdohm/de-crast#18]
Expected Behavior: When selecting "Create Task" after filling out the information, the information should be wiped from the local display or navigation could move back to the home screen

Actual behavior: Create Task can be clicked multiple times to create multiple instances of the same task

How can the problem be reproduced: Fill out information to create task, then click Create Task as many times as you want

Operating System: Windows 8, Chrome

Severity: Minor User Experience design flaw

**Comment by tsealex** [comment]
This happens in browsers only because the app isn't able to schedule a notification event, which results in an internal error, causing the app to stay in the task view.
