### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by yifeifeng** [timdohm/de-crast#5]
Summary: For Notification, name of the user A who invited user B is shown as none in B's client.
 
Description: For example, User A created a new task and invited user B to view this task. Under Notification manual in B' client , there is a line "None sent you an invite for viewing the task "task name"" .

Expected Behavior: The "None" should be the name for User A.

Severity: critical

Operating System: Firefox web browser

Image:
![image](https://cloud.githubusercontent.com/assets/17976613/25552282/ddd76994-2c5a-11e7-844f-6fefd8417d7b.png)

**Comment by yifeifeng** [comment]
Notification mechanism is not involved in Android deceive which means  I am not able to see the notification other than constantly check the "Notification" tab inside this app.

**Comment by tsealex** [comment]
I am no longer able to reproduce this error.
