### ISSUE TITLE
Facebook Login issues

### ISSUE THREAD

**Issue by syncnj** [timdohm/de-crast#6]
Summary: The implementation of login with Facebook is not robust.

Description: 
We have 3 users: all three of the users have been approved/ added into the approval list.
    Using the browser version of the client app:
        User 1 & 2 are able to log in the app using the browser version. 
        User 3 are not even able to log in. After typing in the email and the password, the browser app will always pop up with the message: "Facebook error: undefined". And the user cannot do anything with the app.
    User 3's error window looks like this:
![image](https://cloud.githubusercontent.com/assets/5064526/25552208/5dbf2572-2c59-11e7-936c-53bcdeecb1c1.png).

We also tested the Android version of the app:
        We're using the apk installer provided by Junwei Wu, running on both Samsung Galaxy S6 Edge (6.0.1) and Google Pixel XL (7.1.2). And none of the 3 users are able to successfully log in.
         We're experiencing this error after typing in the email and the password: The login window will disappear, and the app is still showing the "Login with Facebook" button. (For our guess, it looks like it's not logged in), and no way to proceed to the next window. 
        (UPDATED: see follow-up below.)
Severity: Blocker (UPDATED: now should be low).

Comments:
    The user 3 who are not able to log in enabled 2-Factor Authentification. We don't know if this will relates to the issue, but it might be the cause of it.

**Comment by syncnj** [comment]
With an updated version of Android App. All 3 users are now able to log in correctly. 
Still same issue for the browser part.

**Comment by timdohm** [comment]
Facebook error is due to expired auth_token. Function added to force user to re-login when token is expired.
