### ISSUE TITLE
Wrong due date when viewing friends' task

### ISSUE THREAD

**Issue by yifeifeng** [timdohm/de-crast#7]
Summary: when viewing friends' task, I found due dates of all friends' tasks are wrong.

Description: All due dates for friend's tasks are Jan 18, 1970.  When viewing friend's task list, all due dates are incorrect.  However, when clicking into one of those tasks,  all the due dates are exactly "Jan 18, 1970 6:52:08 AM", which is obviously incorrect.  Furthermore, all tasks can be sorted correctly when selecting sort by due date( I believe that all due dates are stored correctly but are not displayed correctly).

Severity: blocker

Operating System: Firefox web browser

Image:
Wrong date 
![image](https://cloud.githubusercontent.com/assets/17976613/25552459/f2d32dec-2c5f-11e7-9a0c-9ea5c2f2a5cd.png)

Wrong date inside a task
![image](https://cloud.githubusercontent.com/assets/17976613/25552289/45657010-2c5b-11e7-8638-e74de9db385d.png)

**Comment by tsealex** [comment]
Interesting, never experienced this before. Does the peoblem also occur in Android?

**Comment by jerryand100** [comment]
I've noticed it in Android before, yes.

**Comment by yifeifeng** [comment]
Yes. Both in Android and Browser.

**Comment by tsealex** [comment]
This issue has been fixed.
